clear; clc;

%Outputs a file with the following fields
%  gen_params - Basically the options set at the top of this file.
%
%  correspondences - a structure of tracklets and pairwise correspondence
%                 lists, and other fields, in the same format as
%                 returned by generate_fake_test_data
%
%  ground_truth - Struct of ground truth cameras
%      .cameras - array of cameras in the format given by the format
%                 generate_fake_groundtruth_cameras.
%



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Option settings
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%What to name the output file
data_output_filename = 'test_bank/trash.mat';

%Make the data predictibly random by setting a manual seed. Change it to
%make different data.
gen_settings.rngseed = 1;

rng(gen_settings.rngseed);

%The number of a camera configuration
gen_settings.camera_config_number = 1;

%Set this to 1 to see what happens with one track. Set
% to 100-1000 to start seeing statistically meaningful results.
%Note some of these tracks (depending on settings below) will overlap
%in time windows and create more false correspondences.
gen_settings.number_of_tracks = 20;
%gen_settings.number_of_tracks = 10;

%This is sort of "starting point" for track velocity, probably
%leave it at 1 for now
gen_settings.track_velocity_factor = 1;

% Increasing this makes lines more curvy, and points will speed up and
% slow down. 0 = straight lines, constant velocity.
gen_settings.track_non_constant_factor = 1; 
%gen_settings.track_non_constant_factor = 0.2;
%gen_settings.track_non_constant_factor = 0.02;
%gen_settings.track_non_constant_factor = 0;
    
% Increasing this makes observations noisier. Observations are taken
% from the curvy path and gaussian noise is added. 0 = no noise.
% 1 is my usual value.
gen_settings.track_observation_variance_scale = 1;
%gen_settings.track_observation_variance_scale = 0.2;
%gen_settings.track_observation_variance_scale = 0.02;
%gen_settings.track_observation_variance_scale = 0;

% As set, we will see correspondences of 1 path 30% of the time,
% two paths 40% of the time, and 3 paths 30% of the time. To never
% have errors, set this to 1 path only [1.01 0 0]. Errors come from
% having multiple paths that give false correspondences.
gen_settings.multiple_objects_collision_percentiles = [1.01 0 0];
%gen_settings.multiple_objects_collision_percentiles = [0.3 0.7 1.01];

%Up to N tracks in window:
%The following was generated by using PMF 0.8^(1:N) / sum(0.8^1:N),
%i.e. each bin has 80% probability of the previous
% N = 10;
% gen_settings.multiple_objects_collision_percentiles = ...
%    cumsum(0.8.^(1:N) / sum(0.8.^(1:N))) + 0.001

%Up to 10 tracks in window:
%The following was generated by using PMF 0.8^(1:10) / sum(0.8^1:10),
%i.e. each bin has 80% probability of the previous
%gen_settings.multiple_objects_collision_percentiles = [0.2241,...
%    0.4033    0.5467    0.6614    0.7532    0.8266    0.8853,...
%    0.9323    0.9699    1.0001];


%When the collision percentiles allow for multiple tracks at the same
% time, this will dictate how often in the collision that any track
% has only one tracklet.  Set this near 0 for mostly tracks that intersect
% pairs of camera views, and set it to 1 for tracks that intersect
% mostly single camera views.
gen_settings.multiple_correspondence_percentage_single_tracklets = 0.3;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Include Paths
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
addpath('./lib/mds_map/');
addpath('./lib/LMFnlsq/');


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Make Ground Truth Cameras if Generating fake data
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

cameras = generate_fake_groundtruth_cameras(...
                            gen_settings.camera_config_number);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Start making tracklets / making plot if generating fake data.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

figure(1);
clf;
hold on;
[ correspondences, ground_truth ] = ...
      generate_fake_test_data(cameras,...
                              gen_settings.number_of_tracks, ...
                              gen_settings.track_velocity_factor, ...
                              gen_settings.track_non_constant_factor, ...
                              gen_settings.track_observation_variance_scale, ...
                              gen_settings.multiple_objects_collision_percentiles, ...
                              gen_settings.multiple_correspondence_percentage_single_tracklets, ...
                              true); %with plot

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Create output file
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


generation_settings = gen_settings

save(data_output_filename,'correspondences','ground_truth',...
                          'generation_settings');